<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ChangeRoleRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'username' => 'required',
            'role' => 'required|exists:roles,id'
        ];
    }

    public function messages()
    {
        return [
            'username.required' => 'Obavezan unos korisničkog imena',
            'role.required' => 'Obavezno odabrati ulogu',
            'role.exists' => 'Ne postoji uloga'
        ]; // TODO: Change the autogenerated stub
    }
}
