<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class ContactRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'desc' => 'required|min:10',
            'title' => 'required|min:4',
            'email' => 'required|email'
        ];
    }

    public function messages()
    {
        return [
            'desc.required' => 'Opis je obavezan',
            'desc.min' => 'Opis mora biti duži od :min karaktera',
            'title.min' => 'Naslov mora biti duži od :min karaktera',
            'title.required' => 'Naslov je obavezan',
            'email.required' => 'Email je obavezan',
            'enail' => 'Format mejla nije obavezan'
        ]; // TODO: Change the autogenerated stub
    }
}
