<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class CreateCommentRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'comment-area' => 'required|min:5'
        ];
    }

    public function messages()
    {
        return [
            'comment-area.required' => 'Obavezan unos komentara',
            'comment-area.min' => 'Komentar mora biti duži od :min karaktera'
        ]; // TODO: Change the autogenerated stub
    }
}
