<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class EditPostRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'title' => 'required|min:6',
            'desc' => 'required|min:10'
        ];
    }
    public function messages()
    {
        return [
            'title.required' => 'Obavezan unos naslova',
            'title.min' => 'Naslov mora biti duži od :min karaktera',
            'desc.required' => 'Obavezan unos opisa',
            'desc.min' => 'Opis mora biti duži od :min karaktera'
        ]; // TODO: Change the autogenerated stub
    }
}
