<?php

namespace App\Http\Requests;

use Illuminate\Foundation\Http\FormRequest;

class FileRequest extends FormRequest
{
    /**
     * Determine if the user is authorized to make this request.
     *
     * @return bool
     */
    public function authorize()
    {
        return true;
    }

    /**
     * Get the validation rules that apply to the request.
     *
     * @return array
     */
    public function rules()
    {
        return [
            'file' => 'file|mimes:png,gif,jpg,jpeg|max:3000'
        ];
    }

    public function messages()
    {
        return [
            'file' => 'Fajl za unos je obavezan',
            'file.mimes' => 'Ekstenzija mora biti png, gif, jpg ili jpeg',
            'files.max' => 'Fajl mora biti manji od 3mb'
        ]; // TODO: Change the autogenerated stub
    }
}
